import 'package:get/get.dart';
class Localstring implements Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys =>{
   'en':{
    "1":"phone number",
    "2":"password",
    "3":"Login",
    "4":"Arabic",
    "5":"English",
    "6":"languash",
    "7":"Log out",
    "8":"Category",
    "9":"Heart",
    "10":"Painkillers",
    "11":"Vitamins",
    "12":"Chemical",
     "13":"enter medicine",
     "14":"Home",
     "15":"Orders",
     "16":"Setting",
     "17":"enter your password",
     "18":"enter your phone number",
     "19":"Language",
     "20":"Choose Language",
     "21":"Addition",
     "22":"Enter the medicine you are looking for",
     "23":"scientifc name",
     "24":"commercial name",
     "25":"category id",
     "26":"Category",
     "27":"price",
     "28":"date",
     "29":"manufacture",
     "30":"Quantity",
     "31":"Are you sure",
     "32":"Warning",
     "33":"ok",
     "34":"cancle",
     "35":"Add medication",
     "36":"Added successfully",
     "37":"Order status:",
     "38":"Payment status:",
     "39":"In preparation",
     "40":"sent",
     "41":"Received",
     "42":"paid",
     "43":"unpaid",
     "44":"ERROR",
     "45":"Something went wrong",
     "46":"Heart medications",
     "47":"Chemical medications",
     "48":"Painkillers medications",
     "49":"Vitamins medications",

     


    

   },
   'ar':{
    "1":"رقم الموبايل" ,
    "2": "كلمة السر",
    "3":" تسجيل دخول",
    "4":"عربي",
    "5":"انكليزي",
    "6":"لغة",
    "7":"تسجيل خروج",
    "8":"التصنيفات",
    "9":"قلبية",
    "10":"مسكنات",
    "11":"فيتامينات",
    "12":"كيميائية",
    "13":"ادخل الدواء",
    "14":"الرئيسية",
     "15":"الطلبيات",
     "16":"الضبط",
     "17":"ادخل كلمة السر",
     "18":"ادخل رقمك",
     "19":"اللغة",
     "20":"اختر اللغة",
     "21":"إضافة",
     "22":"ادخل الدواء الذي تبحث عنه",
     "23":"اسم علمي",
     "24":"اسم تجاري",
     "25":"رقم التصنيف",
     "26":"التصنيف",
     "27":"السعر",
     "28":"التاريخ",
     "29":"الشركة المصنعة",
     "30":"الكمية",
     "31":"هل أنت متأكد",
     "32":"تنبيه",
     "33":"تم",
     "34":"إلغاء",
     "35":"أضف دواء",
     "36":"تمت الإضافة بنجاح",
     "37":"حالة الطلب :",
     "38":"حالة الدفع :",
     "39":"قيد التحضير",
     "40":"تم الارسال",
     "41":"مستلمة",
     "42":"تم الدفع ",
     "43":"غير مدفوع",
     "44":"تنبيه",
     "45":"هناك  شيء غير صحيح",
     "46":"أدوية قلبية",
     "47":"أدوية كيميائية",
     "48":"المسكنات",
     "49":"الفيتامينات",



   }
  };

}